// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     VehicleUpdated.avsc
 */

package events

import (
	"io"

	"github.com/actgardner/gogen-avro/container"
)

type VehicleUpdated struct {
	Id        string
	Latitude  float64
	Longitude float64
	Producer  string
	CreatedAt int64
	Comments  string
}

func DeserializeVehicleUpdated(r io.Reader) (*VehicleUpdated, error) {
	return readVehicleUpdated(r)
}

func NewVehicleUpdatedWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &VehicleUpdated{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func NewVehicleUpdated() *VehicleUpdated {
	v := &VehicleUpdated{}

	return v
}

func (r *VehicleUpdated) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"latitude\",\"precision\":8,\"scale\":2,\"type\":\"double\"},{\"name\":\"longitude\",\"precision\":6,\"scale\":8,\"type\":\"double\"},{\"name\":\"producer\",\"type\":\"string\"},{\"name\":\"createdAt\",\"type\":\"long\"},{\"name\":\"comments\",\"type\":\"string\"}],\"name\":\"VehicleUpdated\",\"namespace\":\"com.ricardohsd.events\",\"type\":\"record\"}"
}

func (r *VehicleUpdated) Serialize(w io.Writer) error {
	return writeVehicleUpdated(r, w)
}
